---
title: "Observation bias"
author: "Cyril Matthey-Doret"
date: "August 17, 2016"
output: ioslides_presentation
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
auto_processed <-read.table("/home/cyril/Documents/Internship/chalcid_comparative_analysis/Data/R_working_directory/auto/auto_processed_data.csv", header = T, sep= ",")
manual_processed <-read.table("/home/cyril/Documents/Internship/chalcid_comparative_analysis/Data/R_working_directory/manual/manual_processed_data.csv", header = T, sep= ",")
library(ggplot2);library(gridExtra);library(lattice);library(MASS);library(car)
```

##Study bias issue:

```{r eruptions}
inputPanel(
  sliderInput("cutoff", label = "Minimum number of locations:",
              min = 0, max = 100, value = 1, step = 1)
)

renderPlot({
  ggplot()+
  geom_boxplot(data = auto_processed[!is.na(auto_processed$mode) & auto_processed$nbr_country>input$cutoff,],aes(x=mode,y=pmin(lat_max-lat_min)))+
  ggtitle("Latitude range: Overall")+
  labs(x="Reproduction mode",y="Latitude")+
  annotate(x = c(1.1,2.1),y=c(10,10),geom= "text", label=c(paste0("n=",length(auto_processed[auto_processed$mode=="asex" & auto_processed$nbr_country>input$cutoff,"lat_max"])),                            paste0("n=",length(auto_processed[auto_processed$mode=="sex" & auto_processed$nbr_country>input$cutoff,"lat_max"]))))+
  theme_bw()
})
```

##Study bias issue 2:

```{r qqplot}
inputPanel(
  sliderInput("qqcutoff", label = "Minimum number of locations:",
              min = 0, max = 100, value = 1, step = 1)
)

renderPlot({
  poisson <- fitdistr(auto_processed$nbr_country[!is.na(auto_processed$mode) & auto_processed$nbr_country>input$qqcutoff],       "Poisson")
  qqp(main="Poisson",auto_processed$nbr_country[!is.na(auto_processed$mode) & auto_processed$nbr_country>input$qqcutoff],         "pois", poisson$estimate)

})

```



##Study bias issue 3:

```{r densiplot}
inputPanel(
  sliderInput("denscutoff", label = "Minimum number of locations:",
              min = 0, max = 100, value = 1, step = 1)
)

renderPlot({
  densityplot(auto_processed$nbr_country[auto_processed$nbr_country>input$denscutoff])
})
```



This R Markdown presentation is made interactive using Shiny. The viewers of the presentation can change the assumptions underlying what's presented and see the results immediately. 

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).


## Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## R Output

```{r cars}
summary(cars)
```


